### ISSUE TITLE
analyze_TOI1452 

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-utils#1]
hi, here's what I did:
1- wget http://www.astro.umontreal.ca/~artigau/all_ccfs/TOI-1452_sanitize_mask_Gl846_neg_ccf.tar
2- downloaded all ccf_tools today
3- in python, import analyze_TOI1452.py

It fails at this point: 
    tbl1 = get_object_rv(object,mask = 'gl699_neg',method = 'template',force = True,exclude_orders = exclude_orders,snr_min = 20.0,sanitize = True, weight_type = 'ccf_depth')
with the error:

  File "/Users/clairemoutou/apero/scripts/ccftools/ccf2rv.py", line 207, in get_object_rv
    keep = tbl['EXTSN035']>snr_min
  File "/Users/clairemoutou/anaconda3/lib/python3.7/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/Users/clairemoutou/anaconda3/lib/python3.7/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'EXTSN035'

Does anyone know what is wrong?
thanks!

**Comment by clairem789** [comment]
ok the trick was to remove the - from the object name, to match the directory name that I had given. thanks

**Comment by clairem789** [comment]
next error is in a figure:
  File "analyze_TOI1452.py", line 33, in <module>
    plt.errorbar(tbl_bin1['MJDATE_MEAN'], tbl_bin1['RV'],yerr=tbl_bin1['ERROR_RV'], linestyle="None", color = 'red',
  File "/Users/clairemoutou/anaconda3/lib/python3.7/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/Users/clairemoutou/anaconda3/lib/python3.7/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'ERROR_RV'

**Comment by pfouque58** [comment]
I got this:
(venv) spdrs@apiki:/data/spirou3/CCF2RV_EA$ python
Python 3.7.7 (default, May  6 2020, 11:43:34) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from analyse_TOI1278 import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/spirou3/CCF2RV_EA/analyse_TOI1278.py", line 7, in <module>
    from per_epoch_table import per_epoch_table
ModuleNotFoundError: No module named 'per_epoch_table'
>>> 

Where can I get the per_epoch_table package?

Thanks

**Comment by eartigau** [comment]
It's one of the codes in the GitHub folder.

**Comment by pfouque58** [comment]
ah ok I have to download the code again: how can I synchronize your changes on my installation using git?

**Comment by eartigau** [comment]
It's with a git pull origin master. It's probably best that you ask Neil for a little demo, I have it set up locally, but that required some help from him. Also, consider using PyCharm for Mac, it works nicely with GitHub.

**Comment by pfouque58** [comment]
OK thanks I ask Neil

**Comment by eartigau** [comment]
You need to update both codes. This value was not returned by previous versions of the get_object_rv.

**Comment by pfouque58** [comment]
Thanks I got help from Neil and updated all apero-utils. You can truly close this issue
