### ISSUE TITLE
[NIRPS] Problem with raw data at UdeM 2023-06-14 to 2023-06-19

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#122]
I  see some random files in /nirps_raw/nirps/tmp-reads  (from 2023-04) are these stuck there or are we really getting new data from April?

Also I'm getting an error on a file:
```
14:03:29.195-@!|PROC| Error<class 'PermissionError'>: [Errno 13] Permission denied:
14:03:29.195-@!|PROC|   '/cosmos99/nirps/apero-data/nirps_he_07276_online/raw/2023-06-14/NIRPS_2023-06-14T12_10_34_132.fits
```

Also I can't open it with dfits. Not sure whats wrong with it its 289M so it looks like the right size but may be corrupted

Also have files with > 300M appearing in nights of 14th, 16th, 17th, 18th, and 19th June.

These lead to to reduction getting stuck on "infinite headers"

**Comment by njcuk9999** [comment]
For now this means we cannot reduce data until this is solved.

@vandalt hopes to having it fixed by Monday 26th.

**Comment by vandalt** [comment]
> Also I can't open it with dfits. Not sure whats wrong with it its 289M so it looks like the right size but may be corrupted

For that file, the issue is the permission. Not sure what happened there, but relatively easy to add a check for this and automatically remove the files.

```bash
(base) [nirps-admin@maestria nirps]$ ls -l /cosmos99/nirps/apero-data/nirps_he_07276_online/raw/2023-06-14/ -l
total 11816812
-rw-r--r-- 1 nirps-admin nirps 302071680 Jun 20 03:27 NIRPS_2023-06-14T12_08_53_802.fits
-rw------- 1 nirps-admin nirps 302071680 Jun 20 12:30 NIRPS_2023-06-14T12_10_34_132.fits
-rw-r--r-- 1 nirps-admin nirps 302071680 Jun 20 03:30 NIRPS_2023-06-14T12_12_25_610.fits
```

Regarding files larger than  289M, fitsort seems to print this warning when opening them:

```bash
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: Header block contains null bytes instead of spaces for padding, and is not FITS-compliant. Nulls may be replaced with spaces upon writing. [astropy.io.fits.header]
WARNING: VerifyWarning: Error validating header for HDU #5 (note: Astropy uses zero-based indexing).
    Header size is not multiple of 2880: 29923119
There may be extra bytes after the last HDU or the file is corrupted. [astropy.io.fits.hdu.hdulist]
Filename: /nirps_raw/nirps/raw-data/nirps_he/2023-06-14/NIRPS_2023-06-14T13_07_02_876.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     756   ()      
  1  slope         1 ImageHDU        10   (4096, 4096)   float64   
  2  intercept     1 ImageHDU        10   (4096, 4096)   float64   
  3  n             1 ImageHDU        12   (4096, 4096)   int16 (rescales to uint16)   
  4  posemeter     1 BinTableHDU     20   50R x 3C   [1D, 1D, 1D]
```

Not sure what it means. But anyways not all oversized files have this behaviour. Some just can't be opened at all (or take longer than my patience before clicking ctrl+c).

My plan for this would be to write a simple independent script checking the following periodically:

1. Was any data downloaded in the last two days? -> If not email people (allows us to catch hanging script)
2. Do some files have bad permissions?  -> delete and email with list of files
3. Are some ramps bigger than 289 Mb? -> delete and email with list of files

Would this be OK @njcuk9999 ? Do you have other suggestions?

**Comment by vandalt** [comment]
Actually, I'll add a 4th item: compare the latest two nights with the table I generate from the ESO archive. That way we also have a diff of what should be on disk but is not. I think @YuriMessias is working on a similar script which would be independent from mine, but I think having a non-independent version would already be helpful: the buggy part seems to be more the download than getting a list of files.

**Comment by vandalt** [comment]
I took a closer look at this. Points 1 and 2 were straightforward to implement.

3 is a bit more tricky: some files are just above 289M, among them some cause warnings in `fitsinfo` or `fits.info()`, some cause nothing, and some cause infinite (or at least very long) loops. However, for all those cases, when I re-downloaded the file, it came back with size 289M. So they were probably all corrupt at least a little. It seems the safest option is to re-download the file systematically if the size is too large.

However, thinking a bit more about this, automatically deleting the files might be dangerous (e.g., was if a trigger script had already launched their reduction/used them in some way?). I see two solutions for this: 1) run the check right after each download run  and 2) run the check daily, email corrupt files when there are any, and let us delete them manually. @njcuk9999 what do you think for this last point?

**Comment by njcuk9999** [comment]
Yer I think this is all good.
For the email I wouldnt email everyone for all of these as they are "our fault".

I think we would like an email to udem people (Fred is setting up a mailing list) when there has been no data for 2 days (actually we may add our testsfor bad calibration to this). So maybe we need two sets of emails possible one for "problems thag require others to know" and ones just for you/me when something goes wrong our end.

**Comment by njcuk9999** [comment]
As for your last point I think 1. Delete them straight away the reason being the infinite headers completely break the reduction so if they are there the reduction will be broken any way Id rather they just get deleted asap and then at worst apero will crash on that file and move on to the next (if its running at that point).
