### ISSUE TITLE
[NIRPS] Problem with no full calib set 2023-06-19 to 2023-06-30

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#128]

**Comment by vandalt** [comment]
Some other things to note (discussed on Slack but adding here for tracking):

- The full calib set do not seem to be on the ESO archive either
- The data in Geneva is the same (I think they also get the raw data from the archive so this would make sense)
- I suspected that the calibration program ID might have changed, but some calibration data is there and has the same ID as before.

**Comment by njcuk9999** [comment]
We are not sure if a full calibration set was taken during that period of time.
So the cause might be at the observatory. I'm waiting to hear back from @astrobaron to confirm this.

**Comment by vandalt** [comment]
Ok thanks. Should we add a "daily check" to nirps-download (vandalt/nirps-download#10) that checks for a given list of calib file (based on filetype+number, or something else that you define)?

**Comment by astrobaron** [comment]
I sent a bunch of emails

**Comment by njcuk9999** [comment]
Just to comment on @vandalt last message. I think we are going to implement a whole suite of "raw tests" that will be run by someone here in Montreal on a daily basis.

So short answer is no I don't think we should make the nirps-download more complicated and should just try now to make it as good as possible (though feel free to still have your test for no files as that is quite simple).
