### ISSUE TITLE
[NIRPS] Change all paths / references on nirps-client from 07276 to 07 i.e. nirps_he_07276_online --> nirps_he_07_online

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#141]
APERO profiles with a version in doesn't make sense.
Also online and offline having the same apero install directory doesn't make sense

Need to change the following profiles

- [ ] nirps_he_07276_online  to nirps_he_online
- [ ] nirps_ha_07276_online to nirps_ha_online
- [ ] nirps_he_07276_offline to nirps_he_offline
- [ ] nirps_ha_07276_offline to nirps_ha_offline
- [ ] spirou_07276_online to spirou_online
- [ ] spirou_07276_offline to spirou_offline

Each one of these requires:

- [ ] update database.yaml
- [ ] update install.yaml
- [ ] update .sh files
- [ ] update bash files
- [ ] update user_config.ini
- [ ] update apero-data
- [ ] update lbl-data
- [ ] update .yaml files of manual_trigger / ARI / copy / checks
- [ ] update the wiki

At the same time make two different apero-drs directories 
`apero-drs-online`
`apero-drs-offline`

So we can have different branches on each.

Also rename `apero-bin` directory `git-bin`   (as these are all github repos)

We may need `apero-env-07` duplicated (if I need a different env between online and offline) but I'll leave this until its needed as then I have to think about what conda env apero-utils are on.

**Comment by njcuk9999** [comment]
@CharlesCadieux I think you should follow this.

Let me know if you think there are any other things that have these references in or anything that will break with these changes.


@vandalt  let me know if renaming `apero-bin` directory will break `nirps-download` and what I need to change to make it not break.

I wont do this just yet but I think the slight reshuffle should be better for the long term

**Comment by vandalt** [comment]
Nothing in the Python code would break, but the scripts and crontab specific to UdeM will break, we just need to change a few lines. Let me know when I should change this (`nirps-download` issue: vandalt/nirps-download#18)

**Comment by njcuk9999** [comment]
okay I've changed `apero-bin` to `git-bin` I'll try to update the paths on my end ASAP
