### ISSUE TITLE
[APERO] Problem with background

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#148]
Structures seen in some time series in APERO extracted files (no telluric correction).
Not seen in Geneva pipeline.

**Comment by eartigau** [comment]
corrected the background issue with a change in the filtering size of scattered light in the NIRPS config file. The previous size (32pix) lead to numerical instabilities as there were just a few pixels considered as 'background' for some boxes. Changing to 256 pix (in area, factor 64 in size) solved the issue.

**Comment by njcuk9999** [comment]
Code is implemented in v0.7.287 (commits: 706b0f93033ef54ad9c3879549a57a4fb60ae265 and 2cc501a3592027fbc12bdfbc43bd80da6ee82834)
