### ISSUE TITLE
Negative gaussian width

### ISSUE THREAD

**Issue by pfouque58** [njcuk9999/apero-utils#16]
It happens that some values of the gaussian width are negative. Maybe a simple bug.

[GJ1002_mask_gj1002_neg_gaussian_template_bisector_20_80_RV.pdf](https://github.com/njcuk9999/apero-utils/files/5404478/GJ1002_mask_gj1002_neg_gaussian_template_bisector_20_80_RV.pdf)

**Comment by vandalt** [comment]
This indeed looks like a small bug. No bounds were placed on the Gaussian parameters in `curve_fit`, leading to some points having width < 0. I will create a PR fixing this.

**Comment by vandalt** [comment]
Solved by #19 .
