### ISSUE TITLE
[APERO] SNR difference between APERO/ESO Pipeline

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#161]
There seems to be a significant deviation between the APERO and ESO pipelines for SNR (with the biggest difference at low SNR).

@CharlesCadieux  could you add the two plots here you showed.

The ETC was calibrated with ESO reduced data so hard to tell whether we are just seeing the ESO SNR agree with the ETC or whether something is going wrong with APERO.

As far as I recall the SNR is calculated slightly differently (but only in terms of region size and location) so extracted spectra should be the same.

**Comment by njcuk9999** [comment]
For reference APERO uses the following code:

```python
def calculate_snr(e2ds, blaze_width, r1, r2, sigdet):
    # get the central pixel position
    cent_pos = int(len(e2ds) / 2)
    # get the blaze window size
    blaze_lower = cent_pos - blaze_width
    blaze_upper = cent_pos + blaze_width
    # get the average flux in the blaze window
    flux = mp.nansum(e2ds[blaze_lower:blaze_upper] / (2 * blaze_width))
    # calculate the noise
    noise = sigdet * np.sqrt(r1 + r2)
    # calculate the snr ratio = flux / sqrt(flux + noise**2)
    snr = flux / np.sqrt(flux + noise ** 2)
    # return snr
    return snr, flux
```



Where:
```
sigdet = HIERARCH ESO DET OUT1 RON
blaze_width = 50
r1 = r2 = 9       # for fiber A
```

and `e2ds` is the extracted spectrum prior to flat correction.

**Comment by njcuk9999** [comment]
@RomainAllart Do you know where the calculation for the ESO pipeline is? I'd like to confirm how different our two calculations are.

**Comment by RomainAllart** [comment]
I looked quickly at the NIRPS pipeline user manual but I did not find how the SNR is calculated exactly. We can search in the C code or ask Danuta.
 https://www.eso.org/sci/facilities/lasilla/instruments/nirps/doc.html

**Comment by njcuk9999** [comment]
- [ ] calculate SNR on Geneva data using APERO  SNR function  (@CharlesCadieux )
- [ ] Work out the true SNR (differentially) - only doable for files in a time series (@CharlesCadieux )
- [ ] median flux level of raw files (@eartigau to provide code) and compare to H band flux from extracted files Geneva and APERO  (@CharlesCadieux )

**Comment by CharlesCadieux** [comment]
SNR on Geneva data using APERO SNR function


[snr_apero_vs_espresso.pdf](https://github.com/njcuk9999/apero-utils/files/12295519/snr_apero_vs_espresso.pdf)
