### ISSUE TITLE
Results from analyse_TOI1278.py

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#2]
Please use the following Issue to add plots / add comments on results obtained by running:
`apero-utils/spirou/sandbox/ccf_tools/analyse_TOI1278.py`

Any problems please post in a new Issue to be solved quicker / closed when solved.

Note to add plots:

update to somewhere or put here: https://github.com/njcuk9999/apero-utils/tree/master/general/imagedump/

and use the following code to display them in an issue:
```
![alt text](http://url/to/img.png)
```

i.e.
```
![apero](https://raw.githubusercontent.com/njcuk9999/apero-utils/master/general/imagedump/apero_logo.png)
```

![apero](https://raw.githubusercontent.com/njcuk9999/apero-utils/master/general/imagedump/apero_logo.png)

Note for  analyse_TOI1452 see Issue #3

**Comment by clairem789** [comment]
I tried the analyse_TOI1278.py code on sep 25. It worked fine and gave this result:

Order 37 has a CCF full of NaNs. Added to the rejected orders 
The CCF of order 42 has its minima 29.50 km/s from median CCF, above threshold of +-3.00 km/s


Template CCF iteration number   1, rms RV change 1.2978 km/s for this step
Template CCF iteration number   2, rms RV change 0.2173 km/s for this step
Template CCF iteration number   3, rms RV change 0.0157 km/s for this step
Template CCF iteration number   4, rms RV change 0.0035 km/s for this step
Template CCF iteration number   5, rms RV change 0.0022 km/s for this step
Template CCF iteration number   6, rms RV change 0.0006 km/s for this step
Template CCF iteration number   7, rms RV change 0.0010 km/s for this step
Template CCF iteration number   8, rms RV change 0.0003 km/s for this step
Template CCF iteration number   9, rms RV change 0.0006 km/s for this step
Template CCF iteration number  10, rms RV change 0.0003 km/s for this step
Template CCF iteration number  11, rms RV change 0.0004 km/s for this step
Template CCF iteration number  12, rms RV change 0.0003 km/s for this step
Template CCF iteration number  13, rms RV change 0.0003 km/s for this step
Template CCF iteration number  14, rms RV change 0.0003 km/s for this step
Template CCF iteration number  15, rms RV change 0.0003 km/s for this step
Template CCF iteration number  16, rms RV change 0.0003 km/s for this step
Template CCF iteration number  17, rms RV change 0.0002 km/s for this step
Template CCF iteration number  18, rms RV change 0.0002 km/s for this step
Template CCF iteration number  19, rms RV change 0.0002 km/s for this step
Template CCF iteration number  20, rms RV change 0.0002 km/s for this step


For epoch MJD = 58999.60, the biggest outlier is at 1.196 median abs deviation
For epoch MJD = 59002.57, the biggest outlier is at 1.268 median abs deviation
For epoch MJD = 59004.54, the biggest outlier is at 7.641 median abs deviation
For epoch MJD = 59005.52, the biggest outlier is at 3.993 median abs deviation
For epoch MJD = 59007.52, the biggest outlier is at 1.854 median abs deviation
For epoch MJD = 59008.48, the biggest outlier is at 18.376 median abs deviation
For epoch MJD = 59009.54, the biggest outlier is at 1.520 median abs deviation
For epoch MJD = 59010.61, the biggest outlier is at 3.043 median abs deviation

The binned table has 8 distinct epochs

Amplitude of the sinusoidal at 14.4 days: 2.3395153137099816 m/s
Mean/Median per-epoch STDDEV 0.019903756730697022/0.0196742334997727 m/s

(I guess these should read km/s)

Same as everyone?

**Comment by eartigau** [comment]
yes, they are km/s. Updated

**Comment by edermartioli** [comment]
Below are my results on TOI-1278, first for all bandpasses (YJHK), and then  HK. 

Based on the values of RMS and MAD, the best configuration for this target is when using the mask Gl514_neg.mas, with a slight improvement for HK compared to YJHK. 

The masks  Gl699_pos.mas and Gl846_pos.mas give really bad results. 

******
YJHK
******
TOI-1278__Gl514_neg.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.10+-0.18 d K=2.284+-0.028 km/s rms=57.3 m/s mad=37.4 m/s
TOI-1278__Gl687_neg_depth.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.12+-0.21 d K=2.184+-0.031 km/s rms=62.8 m/s mad=36.3 m/s
TOI-1278__Gl699_neg.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.50+-0.31 d K=2.288+-0.048 km/s rms=84.7 m/s mad=72.2 m/s
TOI-1278__Gl699_pos.mas__tcorr__0.6.131__YJHK__template.rdb: P=11.66+-0.96 d K=1.510+-0.109 km/s rms=421.9 m/s mad=487.3 m/s
TOI-1278__Gl846_neg.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.27+-0.20 d K=2.307+-0.031 km/s rms=60.8 m/s mad=43.7 m/s
TOI-1278__Gl846_neg_depth.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.24+-0.22 d K=2.299+-0.033 km/s rms=65.2 m/s mad=35.6 m/s
TOI-1278__Gl846_pos.mas__tcorr__0.6.131__YJHK__template.rdb: P=13.60+-0.61 d K=2.064+-0.082 km/s rms=195.4 m/s mad=217.1 m/s
TOI-1278__Gl876_neg.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.26+-0.19 d K=2.320+-0.029 km/s rms=56.2 m/s mad=46.5 m/s
TOI-1278__masque_sept18_andres_trans50.mas__tcorr__0.6.131__YJHK__template.rdb: P=14.30+-0.27 d K=2.170+-0.039 km/s rms=75.3 m/s mad=60.4 m/s
Median RVs: P=14.22+-0.20 d K=2.260+-0.030 km/s rms=59.1 m/s mad=44.3 m/s
![TOI-1278](https://user-images.githubusercontent.com/23633657/94732189-50981f80-033c-11eb-9d5b-76c00643adcb.png)
******
HK
******
TOI-1278__Gl514_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.16+-0.18 d K=2.312+-0.028 km/s rms=56.7 m/s mad=36.1 m/s
TOI-1278__Gl687_neg_depth.mas__tcorr__0.6.131__HK__template.rdb: P=14.45+-0.25 d K=2.255+-0.038 km/s rms=70.1 m/s mad=43.2 m/s
TOI-1278__Gl699_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.57+-0.25 d K=2.271+-0.039 km/s rms=68.3 m/s mad=57.7 m/s
TOI-1278__Gl699_pos.mas__tcorr__0.6.131__HK__template.rdb: P=13.27+-0.54 d K=1.583+-0.055 km/s rms=147.5 m/s mad=146.8 m/s
TOI-1278__Gl846_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.10+-0.19 d K=2.311+-0.030 km/s rms=61.5 m/s mad=38.3 m/s
TOI-1278__Gl846_neg_depth.mas__tcorr__0.6.131__HK__template.rdb: P=14.18+-0.18 d K=2.327+-0.027 km/s rms=55.2 m/s mad=43.5 m/s
TOI-1278__Gl846_pos.mas__tcorr__0.6.131__HK__template.rdb: P=14.01+-0.38 d K=2.243+-0.056 km/s rms=118.8 m/s mad=130.4 m/s
TOI-1278__Gl876_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.34+-0.19 d K=2.372+-0.030 km/s rms=57.0 m/s mad=49.0 m/s
TOI-1278__masque_sept18_andres_trans50.mas__tcorr__0.6.131__HK__template.rdb: P=14.49+-0.31 d K=2.298+-0.047 km/s rms=85.5 m/s mad=55.8 m/s
Median RVs: P=14.26+-0.19 d K=2.296+-0.029 km/s rms=57.3 m/s mad=36.4 m/s
![TOI-1278_HK](https://user-images.githubusercontent.com/23633657/94732332-82a98180-033c-11eb-85be-4582bd71c373.png)

**Comment by eartigau** [comment]
You should be getting residuals at the <30 m/s compared to the fit. I don't why Andres gets a bad fit and I don't know how he created his mask. The overleaf for the paper is here

 https://www.overleaf.com/1589777114jjxgpywfvdnm

Please be ***_sure_*** you downloaded the latest codes from Github, I updated the RV code and it may have fixed some issues.

**Comment by eartigau** [comment]
A MAD at ~40 m/s level is significantly poorer that the latest version of the code

**Comment by edermartioli** [comment]
In https://github.com/njcuk9999/apero-utils/issues/2#issuecomment-701612925 I have used the following commands:

```
python spirou_ccf_analysis.py --pattern=data/TOI-1278/*.fits
python rv_plots.py --pattern=data/TOI-1278/*__YJHK__*.rdb --output=data/TOI-1278/TOI-1278.rdb -fc

python spirou_ccf_analysis.py --pattern=data/TOI-1278/*.fits --bandpass="HK"
python rv_plots.py --pattern=data/TOI-1278/*__HK__*.rdb --output=data/TOI-1278/TOI-1278_HK.rdb -fc
```

Using the following wrapper that I wrote to run Etienne's codes:
https://github.com/edermartioli/spirou-ccf-analysis

**Comment by eartigau** [comment]
we should really host all the codes at a single location, do you mind adding it to sandbox/ccd_tools folder?

**Comment by edermartioli** [comment]
> we should really host all the codes at a single location, do you mind adding it to sandbox/ccd_tools folder?

I agree!  This is still a preliminary version and I had to make changes to your codes, that's why I didn't want to put it in the  sandbox/ccd_tools folder. The changes I made are not in the methods for analysis. I can give some more feedback during the DRS meeting. 

> A MAD at ~40 m/s level is significantly poorer that the latest version of the code
It's because I calculate the residuals without combining data within the same epoch. When combining the epochs I get the following:

P=14.22+-0.08 d 
K=2.320+-0.012 km/s 
rms=8.8 m/s 
mad=10.3 m/s

![TOI-1278_comb-epochs](https://user-images.githubusercontent.com/23633657/94738754-3f541080-0346-11eb-8b5a-10ad75470e67.png)

**Comment by eartigau** [comment]
That's getting pretty close to what we got with the best parameters. For every one, you are all invited to the TOI-1278 paper and I have most people already listed. I'd like to a have a plan full of bullets by Friday and start putting some meat on the bones next week. Feel free to add bullets (no text yet) in view of your efforts.

**Comment by clairem789** [comment]
Nice! if I followed well, you Eder used the tcorr files, without additional sanitization? you confirm? That would mean that searching for the best combination of mask+orders we get similar performance as sanitizing + all orders?

**Comment by edermartioli** [comment]
> Nice! if I followed well, you Eder used the tcorr files, without additional sanitization? you confirm? That would mean that searching for the best combination of mask+orders we get similar performance as sanitizing + all orders?

I used all files that Etienne made available in his script to download the data, and I think for this target there were only tcorr files. But for TOI-1452 (see https://github.com/njcuk9999/apero-utils/issues/3#issuecomment-701625832) there are both sanitized and tcorr, and here's a comparison for cases where there is data for the same mask using both sanitized and tcorr. 

Gl699_neg.mas__sani rms=55.8 m/s mad=17.3 m/s
Gl699_neg.mas__tcorr rms=23.0 m/s mad=30.1 m/s
Gl699_neg.mas__sani__ordexcl rms=18.0 m/s mad=20.5 m/s
Gl699_neg.mas__tcorr__ordexcl rms=21.2 m/s mad=27.2 m/s

Gl725B_neg.mas__sani rms=60.0 m/s mad=17.4 m/s
Gl725B_neg.mas__tcorr rms=24.1 m/s mad=33.4 m/s
Gl725B_neg.mas__sani__ordexcl rms=18.2 m/s mad=17.9 m/s
Gl725B_neg.mas__tcorr__ordexcl rms=24.1 m/s mad=29.2 m/s

Gl846_neg.mas__sani* rms=52.3 m/s mad=30.3 m/s
Gl846_neg.mas__tcorr* rms=26.7 m/s mad=26.2 m/s
Gl846_neg.mas__sani__ordexcl rms=21.6 m/s mad=18.4 m/s
Gl846_neg.mas__tcorr rms__ordexcl=24.6 m/s mad=23.3 m/s

The conclusion is that order-exclusion combined with sanitization seems to do the best. But sanitization doesn't always improve, like in the case of mask Gl846_neg.mas without order-exclusion (*).

**Comment by eartigau** [comment]
In general, I really suggest that we only keep H and K bands only. Overall, Y and J add very little info, and if they have strong outliers, they will mess the mean CCF. This is not so say that we drop Y+J forever, just that as they contain ~5% of the info, we'll look at them later.

**Comment by edermartioli** [comment]
Here's the analysis of TOI-1278 (HK) using RVs binned within the same epoch.

**Conclusion:**  the best result was obtained with the mask Gl876_neg.mas with an RMS=7.0 m/s and MAD=2.5 m/s after removing a sinusoidal orbit of P=14.45+-0.07 d  and K=2.381+-0.010 km/s.

***
command line:
```
python rv_plots.py --pattern=data/TOI-1278/*__HK__*.rdb --output=data/TOI-1278/TOI-1278.rdb -f -c -e
```
***

TOI-1278__Gl514_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.29+-0.07 d K=2.322+-0.010 km/s rms=7.4 m/s mad=11.0 m/s
TOI-1278__Gl687_neg_depth.mas__tcorr__0.6.131__HK__template.rdb: P=14.64+-0.11 d K=2.278+-0.017 km/s rms=10.5 m/s mad=6.0 m/s
TOI-1278__Gl699_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.68+-0.14 d K=2.282+-0.021 km/s rms=13.1 m/s mad=11.9 m/s
TOI-1278__Gl699_pos.mas__tcorr__0.6.131__HK__template.rdb: P=13.53+-0.58 d K=1.635+-0.060 km/s rms=52.9 m/s mad=56.6 m/s
TOI-1278__Gl846_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.23+-0.08 d K=2.322+-0.013 km/s rms=9.1 m/s mad=10.2 m/s
TOI-1278__Gl846_neg_depth.mas__tcorr__0.6.131__HK__template.rdb: P=14.24+-0.08 d K=2.331+-0.011 km/s rms=8.4 m/s mad=8.5 m/s
TOI-1278__Gl846_pos.mas__tcorr__0.6.131__HK__template.rdb: P=13.80+-0.52 d K=2.213+-0.074 km/s rms=61.0 m/s mad=70.6 m/s
TOI-1278__Gl876_neg.mas__tcorr__0.6.131__HK__template.rdb: P=14.45+-0.07 d K=2.381+-0.010 km/s rms=7.0 m/s mad=2.5 m/s
TOI-1278__masque_sept18_andres_trans50.mas__tcorr__0.6.131__HK__template.rdb: P=14.69+-0.19 d K=2.323+-0.030 km/s rms=18.2 m/s mad=13.6 m/s
Median RVs: P=14.36+-0.19 d K=2.310+-0.029 km/s rms=20.1 m/s mad=19.3 m/s

![TOI-1278_all_comb-epochs](https://user-images.githubusercontent.com/23633657/94815852-6277d200-03d1-11eb-9721-8440319f7b80.png)

**Comment by clairem789** [comment]
Trying to follow you... So for the combination Gl514_neg.mas__tcorr* and HK bands, Eder gets  rms=7.4 m/s (I guess the number above is with 4 combined spectra)
While in the same config (minus order 37 which is deemed full of Nans) Etienne's latest analyze_TOI1278 gets stddev(obs-model) = 9.81 m/s - right?
Eder, which other orders did you remove?

**Comment by edermartioli** [comment]
> Eder, which other orders did you remove?
No orders removed initially (exclude_orders=[-1]), except those already removed when selecting HK-bands and the further cleaning applied by Etienne's algorithms.

**Comment by clairem789** [comment]
OK, so the difference may be due to a difference of the sinusoidal model inferred from the same data? (because the period and amplitude are indeed different)
or did I miss something?

**Comment by eartigau** [comment]
not too bad! It looks pretty much like my optimal setup too.

**Comment by clairem789** [comment]
OK, got it. The planet period wasn't adjusted in the model. If I use Eder's value then I recover an rms of 7.53m/s, pretty close. I'm just not sure what the TESS period should be set to, exactly. So it was just the planet model which differed. Nice!

**Comment by clairem789** [comment]
now, a question on the optimal mask. It's surprusing that the result depend that much on the stellar template used to create a mask. Do we have good reasons to understand why Gl876 and Gl514 are best matches to TOI1278 (like similar Teff) or is it more complex?

**Comment by clairem789** [comment]
Etienne, could you pls add the CCF caluclation of TOI-1278 with this mask (attached)?
Could you also include the combo samitized/TOI-1278/Gl876_neg mask to see whether it further improves?
thanks (sorry I'm banned for email communication so abusively using github)
[M2_weighted_RV_-30.mas.txt](https://github.com/njcuk9999/apero-utils/files/5312843/M2_weighted_RV_-30.mas.txt)

**Comment by clairem789** [comment]
note I had to include .txt in the mask file name so that github accepts it. Remove the extension for APERO!

**Comment by renedoyon** [comment]
Nice to see all that discussion! I suggested to Etienne to a add the following metric for judging various iterations: the sigma_eff which is simply the median of all error bars of given time serie, one error bar per visit being the weighted average calculated from the 4 exposures.

**Comment by vandalt** [comment]
Here is what I obtained using the defaults in Étienne's script for TOI-1278. The mask is Gl846_neg, but I see that @edermartioli's result  favor other mask so I will test them soon.
![Screenshot-2020-10-01-11-16-10](https://user-images.githubusercontent.com/35547958/94829047-2005c380-03d8-11eb-801e-b534131cb932.png)

**Comment by pfouque58** [comment]
According to spectral types, Gl846 (M0.5V) and Gl514 (M1V) should be the closest template match to TOI-1278 (M0V). The other templates are from M3V-M4V stars.

**Comment by eartigau** [comment]
One word of warning regarding masks vs tellurics. There's no good reason to use masks that include a telluric rejection here. We use masks on defined on a given star onto other stars with different systemic velocity. The rejected lines end up at random locations, but *not* on domain affected by tellurics.

**Comment by eartigau** [comment]
the _neg masks have absolutely no telluric rejection. If there's a bit of spectrum, then there's a line in the mask!

**Comment by pfouque58** [comment]
Are the masks obtained from templates built using the new v131 telluDB?

Is it possible to get sanitized versions of the spectra?

Nice code, thanks

**Comment by pfouque58** [comment]
I think that the formula for the reduced chi2 should involve squared differences, not just the ratio of the difference to the uncertainties

**Comment by eartigau** [comment]
You mean from 131 ? No, not yet, wait ~1-2 week(s). We just finished Barnard to see if anything bad came out of it and we are now processing the first high-priority stars

If you sanitize at home, yes.

For the chi2, yeah, maybe. Feel free to suggest a change to the arithmetics, it may be wrong.

**Comment by pfouque58** [comment]
More reflection about polarimetric sequences: exposures 2493012-3017: we have positions 123423. 3016-7 are supposedly better than the 3013-4 (grade 2 vs 3) at positions 23. Same for 2493612 repeated as 3616 at position 1. Using Gl514_neg.mas, I get a sigma of 12.7 m/s using all exposures and 15.4 removing the repeated exposures to get a sequence with only 4 exposures at positions 1234. So, it is not straightforward to decide how to combine exposures in case of repeats. More "bad" may be better than less "good".

**Comment by pfouque58** [comment]
> If you sanitize at home, yes.

I don't have the tcorr files at CFHT for the run 20AQ10, so I cannot make the sanitized files

**Comment by eartigau** [comment]
nope, no tcorr, no sanitized, that's clear. We have to work straight from the CCFs and run the CCF codes elsewhere.

**Comment by edermartioli** [comment]
> Using Gl514_neg.mas, I get a sigma of 12.7 m/s using all exposures and 15.4 removing the repeated exposures to get a sequence with only 4 exposures at positions 1234. So, it is not straightforward to decide how to combine exposures in case of repeats. More "bad" may be better than less "good".

I think it's ok what you see @pfouque58  since by adding more (pure spectroscopic) exposures it should improve the photon noise and therefore improve the RV measurements. However, for polarimetry, it's a different story!  It's possible that sequence 1_ _423 provides better polarimetry than 1234. But I would go with  @clairem789  suggestion, where the RO should consider always repeating the whole sequence when something happen in the course of a sequence. The conditions would be bad anyway, and the data won't be wasted since the spectroscopy would still be useful.

**Comment by pfouque58** [comment]
Thanks @edermartioli . These are now the instructions for the observer at CFHT
