### ISSUE TITLE
Wrong identifications in object_query_list.fits: Gl725A and Gl412A

### ISSUE THREAD

**Issue by pfouque58** [njcuk9999/apero-utils#20]
The recent reduction of Gl725A (2020-10-22) may still have problem with the BERV correction although BC_OBJNM is now Gl725A. The resulting CCF looks weird.

[Gl725A_mask_gl725a_neg_gaussian_template_bisector_20_80_sani_CCFs.pdf](https://github.com/njcuk9999/apero-utils/files/5431727/Gl725A_mask_gl725a_neg_gaussian_template_bisector_20_80_sani_CCFs.pdf)

**Comment by njcuk9999** [comment]
I confirm we have not fixed the issues with object names going to Gl699 - but this is extra strange that `BC_OBJNM` is now Gl725A - we need someone to check the `apero-drs/apero/data/core/object_query_list.fits` (its a FITS-BINTABLE) we should look at the entry for Gl725A and see what is going on there.

**Comment by pfouque58** [comment]
I checked it and the entry labelled Gl725A corresponds in fact to Gl725B. There is another entry for Gl725B which is correct.
Gl725A = GAIA DR2 2154880616773521408
Gl725B = GAIA DR2 2154880616772528384

**Comment by pfouque58** [comment]
Same problem with Gl412A: the entry in object_query_list.fits corresponds to Gl412B.
Gl412A = GAIA DR2 778947814402405120 (no parallax and proper motion in DR2)
Gl412B = GAIA DR2 778947608243864320

**Comment by njcuk9999** [comment]
So this is why we really need a human to get a list of Gaia IDs and check them all - I have tried again to automate it but there are always exceptions that do not match up!

**Comment by pfouque58** [comment]
If you give me tools to correct the file object_query_list.fits, I can do that. I don't know if I can edit in TOPCAT and save the corrections

**Comment by njcuk9999** [comment]
I'd prefer a separate list that had been checked by CFHT - I talked to Chris about this.
Note in topcat or python you can export this fits file into a csv file - open it in excel , or convert it to an ascii file - whatever you wish!
