### ISSUE TITLE
Updates to bad odometers

### ISSUE THREAD

**Issue by vandalt** [njcuk9999/apero-utils#28]
As @pfouque58 the odometers marked as "no FP" can be used for RV, but not for corrected only (currently they are always skipped). I will update this and try to define a "convention" to automatically flag this from the object-by-object list when putting objects in the second sheet accessed by the DRS.

List of updates to do:
- Properly handle "no FP"
- Check N files vs list of files to ensure no typos or inconsistencies
- Set up and automatic update from Claire's list to the one used by the code.
- Calibration flag? (@njcuk9999 you mentioned something about this in a meeting but I'm not sure what exactly)

**Comment by njcuk9999** [comment]
Just that you have a sheet for each object - but we may need a sheet for calibration odometer codes (at least for blacklist PP)
they aren't linked to any particular object name
