### ISSUE TITLE
How to get sanitized CCF with a given mask?

### ISSUE THREAD

**Issue by pfouque58** [njcuk9999/apero-utils#4]
I used to have this kind of table from Etienne's CCF_DEMO code: CCFTABLE_2295360o_pp_e2dsff_sanit_AB_GJ1002_neg.fits
Now I need files such as 2497833o_pp_e2dsff_sani_AB_ccf_gl846_neg_AB.fits to run the CCF2RV code with sanitized data.

Could you provide me with such a set for GJ1002?

Thanks and sorry to have to request it from you

**Comment by eartigau** [comment]
In general --->
Option 1: You do it yourself with the ccf_wrap.py. Just change the paths at the start of the code and give it an input table with the mask you want and run it locally
Option 2  : You update the ccf_wrap.tbl on Github so that my code sees it and does the job. Keep an eye on this page to know when it is done: http://www.astro.umontreal.ca/~artigau/all_ccfs/download_ccf.script
Option 2b: This is nice as everyone will see the files and be able to access it.

For this request : I added GJ1002 to the queue with the following lines :

GJ1002, GJ1002_neg.mas, True
GJ1002, GJ1002_neg.mas, False

You will get both sanitized and tcorr versions of the files at the location above in a few hours, check it and run the wget afterwise.

**Comment by pfouque58** [comment]
Thanks for the files. With this I recovered the sinusoidal pattern I had with v0.6.100 and DEMO_CCF code rather than the linear trend I had using the previous version of the CCF2RV code

**Comment by eartigau** [comment]
La grosse classe! That's good news, we may have planet :-) I'd like to see the plot, but as we realized with Claire and our students, you need to be a contributor to add a little demo script on that one. I'll check with Neil, I'm still puzzled as how to add contributors to GitHub.

**Comment by eartigau** [comment]
In principle you should be able to submit a new code to the repository. If it doesn't work, we'll bug Neil.

**Comment by pfouque58** [comment]
OK so now I will try ccf_wrap to get the CCF with the GJ1002_neg mask for 20AQ13, 20AQ15, 20BQ01, 20BQ04, 20BQ06

**Comment by eartigau** [comment]
In the latest reduction at CFHT ?

**Comment by pfouque58** [comment]
Well that's a mix: v0.6.101 for 20AQ13 and 20AQ15-20BQ01, v0.6.130 for 20BQ04 and 20BQ06. I have the tcorr_AB.fits files and the tcorr CCF with Andres mask and would like to create both the tcorr and sani with the correct mask. Maybe you should reopen this issue

**Comment by eartigau** [comment]
wooouuuuu, scary! We'll see if the code survives having a mixture of DRS versions :-| We should probably also run it here in Montreal on an homogeneous set.

**Comment by pfouque58** [comment]
that would be much better. I can send you a list of odometers

**Comment by eartigau** [comment]
Just the target name, corresponding mask and sanitized or not. For a given target, we can generate as many options as you want. Double check that it has not been done yet here:  http://www.astro.umontreal.ca/~artigau/all_ccfs/download_ccf.script

**Comment by eartigau** [comment]
Well, you'll get all the odometers for the target bundled in a big tar. You can delete the odometers you don't want in the folder and run my codes.

**Comment by pfouque58** [comment]
The target GJ1002 is in your all_ccfs directory, this is where I got the tcorr and sanitized data. But these are only old data from 2 years ago (odometers 229*). I send you a list of recent odometers since July 2020 on this same target. It would be nice to see if the sinusoidal trend is confirmed with these new data

**Comment by eartigau** [comment]
The big question is if it was reduced in the latest batch or not. We stopped around the end of June, but we reduced some data up to the 10th of July. Otherwise, all WP1 targets are being reduced all the way to septembre, but that's ongoing. Anyway, I'm adding it to the queue.

**Comment by eartigau** [comment]
It's already done, check the webpage http://www.astro.umontreal.ca/~artigau/all_ccfs/download_ccf.script

You have it with it's own mask and both sanitized options. We don't have more data than that reduced

**Comment by pfouque58** [comment]
J'ai récupéré les données ce matin et ça s'arrête a l'odomètre 2295646
