### ISSUE TITLE
SLS blacklist

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#6]
Claire has started a nice google doc of blacklisted odometer codes.

Please see here (she may need to give you access)

https://docs.google.com/spreadsheets/d/13idu6tx-Zvzp-G9cjOSz-y5FH3E4a0T4Sdlw0235CNs/edit#gid=0

**Comment by eartigau** [comment]
There's a code on GitHub that does the cleaning of bad odometers. You add your bad odometer to the 'blacklist_odo.tbl' on GitHub (check the format in the sample lines) and then you use the check_blacklist.py code:

files = glob.glob('some_search*.fits')
valid_files = check_blacklist(files)


... now, you just need to update the blacklist!

**Comment by njcuk9999** [comment]
Just re-opening this so people see it - only close things when they are not needed any more.
