### ISSUE TITLE
Locked the master - add changes via new branch

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#8]
Hi All,

I've locked the master branch - so you wont be able to make direct changes to it!

So how you edit a file is the following:
command line:
1. make sure current branch (master) is up to date (`>> git pull origin master`)
2. make a new branch  (`>> git checkout -b my_new_branch`)
3. edit a file(s)   (may need to add them via `>> git add my_filename`)
4. commit change (`>> git commit -m "this is why I did this commit"`)
4. push to your branch (`>> git push origin my_new_branch`)
5. when ready to "submit" changes to the master you can create a pull request (in github) and someone else can accept it

github:
1. edit a file
2. commit change to new branch (click ` Create a new branch for this commit and start a pull request. Learn more about pull requests. `)
3. Click "propose changes"

**Comment by vandalt** [comment]
@njcuk9999 I added this info [in the wiki](https://github.com/njcuk9999/apero-utils/wiki/Contributing:-Adding-Changes-on-a-new-Branch), I already had a few other pages so I figured it would be good to start moving the documentation there. Should we close this or leave it open for some time (I assume most people who add code here are now aware of the new workflow)?
